### PR TITLE
ADServicePrincipalName: Added integration test

### LINKED ISSUE #358: ADServicePrincipalName: Integration tests is missing for this resource
We should add integration tests for this resource.

### PR DESCRIPTION
**Pull request by 1800Zeta**
#### Pull Request (PR) description
Adds Integration testing to ADServicePrincipalName. Requires a user account (Sql01Svc) and computer account (IIS01) to exist to add and remove SPNs to.

#### This Pull Request (PR) fixes the following issues
Fixes #358 

#### Task list
- [x] Added an entry under the Unreleased section in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in resource directory README.md.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Conceptual help topic added/updated (cultureFolder\about_ResourceName.help.txt).
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/activedirectorydsc/510)

### CODE REVIEW

**Comment by johlju** [comment]
I have run the integration test for the ADUser resource and that have work, although it might not test all aspects of the resource yet. What did the configuration look like that failed?

**Comment by 1800Zeta** [comment]
I tried various. I was getting errors about plain text passwords in a MOF file. Even though it was going through Convertto-Secure/create credential.

Have you got a really simple example for creating a user? the account doesn't need to be enabled etc hence just running New-ADUser SQL01Svc

**Comment by johlju** [comment]
Aha, when compiling the mof without certificate you need to add `PSDscAllowPlainTextPassword = $true` for example after the `CertificateFile = $env:DscPublicCertificatePath`. I do that manually for now for each test needing to use a credential object.
https://blogs.technet.microsoft.com/ashleymcglone/2015/12/18/using-credentials-with-psdscallowplaintextpassword-and-psdscallowdomainuser-in-powershell-dsc-configuration-data/

So you probably did everything else correct. 😄 

I'm working on (but going very slow) on a way to run test (with a certificate); https://github.com/johlju/ActiveDirectoryDsc/blob/add-integ-documentation/Tests/README.md

**Comment by johlju** [comment]
I haven't added `PSDscAllowPlainTextPassword = $true` in the config files, because I would like us to be secure as the default. Also the test framework can run integration tests using certificate, but we canär run the in the CI because the CI build worker does not support the necessary reboots.

**Comment by 1800Zeta** [comment]
Thank you @johlju I will probably have a look Friday now. And update CHANGELOG.md after the other merge :)

Yeah I have seen the other issue about building up the correct test environment and not supporting reboots etc.

**Comment by 1800Zeta** [comment]
Hi @johlju , the integration tests work fine with the ```PSDscAllowPlainTextPassword = $true``` in the config file (which it currently is). Are you able to review this at all please? If you wish I am happy to take that line out. Thanks

**Comment by johlju** [comment]
@1800Zeta Yes please remove that line.  I rather have the integration tests secure by default in the repo. I will add it back in when I run it in my lab (I haven't added a certificate in my lab either).

I'm planning to add a way to use the test framework to run the integration tests locally (in Hyper-V or similar) which will correctly use a certificate so this row is not needed. But it is a slow progress since most of my time is spent reviewing, which is awesome to get so many PRs! 🙂

**Comment by 1800Zeta** [comment]
Thansk @johlju I have removed the line now. I've seen you doing a lot of reviewing! I've felt guilty for mentioning you on some of the PR's I've done as I know you've been busy. :) Will take a look at other issues as well and see if there is anything else I can pick off once this is finished :)

**Comment by johlju** [comment]
@1800Zeta No worries! Just mention me if you need help with reviews! 🙂  Looking forward to more PRs 😃

**Comment by 1800Zeta** [comment]
Hi @johlju I believe all is done with this one now. Please can you review and test when you get a chance?

**Comment by johlju** [comment]
@1800Zeta Sorry it took so long for me to finish the review. I will merge as soon as the tests passes.

**Comment by johlju** [comment]
@1800Zeta Thank you for this! One more integration test done! 😄

**Pull request merged**
