### PR TITLE
WaitForADDomain: Adds optional parameter WaitForValidCredentials

### LINKED ISSUE #478: WaitforADDomain: Throws an error when credentials are missing
#### Details of the scenario you tried and the problem that is occurring
Running setup of an environment with Domain Controller and couple Windows nodes that should join the domain after it exist. I use `WaitforADDomain` to wait for Domain controller to boot and then `Computer` from `ComputerManagementDsc` renames the server and join the domain under the credentials I provided (the Administrator account is created in the Domain Controller during its boot.
When the domain exists, it finds it but probably the user which is specified in $Credential in Computer resource doesn't exist yet and the log show "The user name or password is incorrect". I tried moving the ADUser creation right after the domain creation but still getting this error (in the previous version this worked as there seemed to be bigger delay before the node discovered the domain?).
What is very weird is after this error, DSC fails with `The SendConfigurationApply function did not succeed` but after 1-2 minutes the nodes actually reboots and joins the domain and the configuration is finished is successful (everything is installed/setup after the reboot).

#### Verbose logs showing the problem
```
[EC2AMAZ-CNTCG1V]:                            [[WaitForADDomain]ForestWait] The Active Directory context will be 
accessed using the 'xxxx\yyyyyy' credentials. (ADCOMMON0048)
Exception calling "FindOne" with "1" argument(s): "The user name or password is incorrect.
"
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : AuthenticationException,Find-DomainControllerFindOneWrapper
    + PSComputerName        : localhost
```

`The machine EC2AMAZ-CNTCG1V successfully joined the domain yyyy-xxxx.local.`

Test-DscConfiguration reports True
```
PS C:\Users\Administrator> Test-DscConfiguration
True
```
#### Suggested solution to the issue
N/A
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```
ADDomain FirstDS
        {
         DomainName = $InternalDomain
         Credential = $default_creds
         SafemodeAdministratorPassword = $restore_credential
         DatabasePath = 'C:\NTDS'
         LogPath = 'C:\NTDS'
         DependsOn = "[WindowsFeature]ADDSInstall"
        }
```

#### The operating system the target node is running
```
OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```
#### Version and build of PowerShell the target node is running
PS 6 is installed
```
PS C:\Users\Administrator> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.592
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.592
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
new ActiveDirectoryDsc 4.0.0.0

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
- Changes to ActiveDirectoryDsc.Common
  - Updated common helper function `Find-DomainController` with the
    optional parameter `WaitForValidCredentials` which will ignore
    authentication exceptions when the credentials cannot be authenticated.
- Changes to WaitForADDomain
  - An optional parameter `WaitForValidCredentials` can be set to $true
    to tell the resource to ignore authentication errors (issue #478).

#### This Pull Request (PR) fixes the following issues
- Fixes #478 

#### Task list

- [x] Added an entry under the Unreleased section in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in resource directory README.md.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Conceptual help topic added/updated (cultureFolder\about_ResourceName.help.txt).
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/activedirectorydsc/481)

### CODE REVIEW

**Comment by X-Guardian** [comment]
Hi @johlju. This functionality will be very useful, but I think a different parameter name would be more useful, such as something like `WaitForADUser`. This would give a better idea of its intended usage.

**Comment by johlju** [comment]
@X-Guardian Happy to change to another name, but it actually ignores authentication errors, it does not wait for a user. My thought was that using `IgnoreAuthenticationErrors` make the user opt-in to potential problems with the provided credential even when the domain is available (but the credentials cannot be used to check that the domain is available). Using the `WaitForADUser` could indicate that the resource is some logic to wait for the correct user to be created and if it is not for a certain of amount of time it will report that it could not be found even if the domain is available which is not possible since we might not have the correct credentials to do that check in the first place. 🤔 

What are your thoughts around this? I thought the opt-in was important in this case. The description for the parameter `IgnoreAuthenticationErrors` is currently 

>Specifies that the resource will not throw an error if authentication fails using the provided credentials and continue wait for the timeout. This can be used if the credentials are known to eventually exist but there are a potential timing issue before they are accessible.

**Comment by X-Guardian** [comment]
Yes, I'm fine with the opt-in, and the description of the parameter. Totally makes sense. If you opt-in though, what the user is wanting to achieve is to wait until the credentials that have been specified are valid, or timeout with an error. Within the module, that is achieved by continuing to wait even if the domain controller responds with an authentication exception, but I feel that for the user, `IgnoreAuthenticationErrors` as a parameter isn't informative of its usage.

**Comment by X-Guardian** [comment]
How about something like `WaitForCredentialValidation`?

**Comment by johlju** [comment]
I like `WaitForCredentialValidation` better, but the word 'validation' still sound a bit towards something the resource have no logic for, but what about `WaitForCredentialToExist`, or `WaitForValidCredentials`?

**Comment by X-Guardian** [comment]
`WaitForValidCredentials` looks good to me.

**Pull request merged**
