### PR TITLE
BREAKING CHANGE: ADManagedServiceAccount: Add KerberosEncryptionType Property and Refactor

### LINKED ISSUE #511: ADManagedServiceAccount: Add KerberosEncryptionType Property
#### Details of the scenario you tried and the problem that is occurring

I am hitting the issue described [here](https://blogs.technet.microsoft.com/joelvickery/cannot-install-service-account-the-provided-context-did-not-match-the-target/) with a Group Managed Service Account created with this resource.

#### Suggested solution to the issue

Add the 'KerberosEncryptionType' property to the `ADManagedServiceAccount` resource that can be used when calling `Set-ADServiceAccount`.

### LINKED ISSUE #512: ADManagedServiceAccount: The Resource will Incorrectly have an Ensure state of 'Absent' if any of its 'PrincipalsAllowedToRetrieveManagedPassword' no longer exist
#### Details of the scenario you tried and the problem that is occurring

For an `ADManagedServiceAccount` resource , if any of the `PrincipalsAllowedToRetrieveManagedPassword` identities on a Group Managed Service Account no longer exist. (A server is decommissioned for example), the `Get-TargetResource` function will return an `Ensure` state of `Absent` for the whole resource. This will cause the LCM to attempt to create the account again, and produce an error as the account already exists.

#### Verbose logs showing the problem

```
{"time": "2019-09-24T16:25:15.475+00:00", "type": "verbose", "message": "[ADFS01-EUW1-SRV]:                            [[ADManagedServiceAccount]AdfsGmsa] Retrieving AD Managed Service Account 'AdfsGmsa'. (MSA0006)"},
  {"time": "2019-09-24T16:25:17.115+00:00", "type": "verbose", "message": "[ADFS01-EUW1-SRV]:                            [[ADManagedServiceAccount]AdfsGmsa] Retrieving Principals Allowed To Retrieve Managed Password based on 'SamAccountName' property. (MSA0013)"},
  {"time": "2019-09-24T16:25:17.459+00:00", "type": "verbose", "message": "[ADFS01-EUW1-SRV]:                            [[ADManagedServiceAccount]AdfsGmsa] AD Managed Service Account 'AdfsGmsa' was not found. (MSA0005)"},
  {"time": "2019-09-24T16:25:17.615+00:00", "type": "verbose", "message": "[ADFS01-EUW1-SRV]:                            [[ADManagedServiceAccount]AdfsGmsa] AD Managed Service Account 'AccountType' is not correct. Expected 'Group', actual ''. (MSA0008)"},
  {"time": "2019-09-24T16:25:17.615+00:00", "type": "verbose", "message": "[ADFS01-EUW1-SRV]:                            [[ADManagedServiceAccount]AdfsGmsa] AD Managed Service Account 'Ensure' is not correct. Expected 'Present', actual 'Absent'. (MSA0008)"},
  {"time": "2019-09-24T16:25:17.631+00:00", "type": "verbose", "message": "[ADFS01-EUW1-SRV]:                            [[ADManagedServiceAccount]AdfsGmsa] AD Managed Service Account 'AdfsGmsa' is NOT in the desired state. (MSA0010)"},
  {"time": "2019-09-24T16:25:17.631+00:00", "type": "verbose", "message": "[ADFS01-EUW1-SRV]: LCM:  [ End    Test     ]  [[ADManagedServiceAccount]AdfsGmsa]  in 2.2490 seconds."},
  {"time": "2019-09-24T16:25:17.631+00:00", "type": "verbose", "message": "[ADFS01-EUW1-SRV]: LCM:  [ Start  Set      ]  [[ADManagedServiceAccount]AdfsGmsa]  "},
  {"time": "2019-09-24T16:25:17.709+00:00", "type": "verbose", "message": "[ADFS01-EUW1-SRV]:                            [[ADManagedServiceAccount]AdfsGmsa] Retrieving AD Managed Service Account 'AdfsGmsa'. (MSA0006)"},
  {"time": "2019-09-24T16:25:17.814+00:00", "type": "verbose", "message": "[ADFS01-EUW1-SRV]:                            [[ADManagedServiceAccount]AdfsGmsa] Retrieving Principals Allowed To Retrieve Managed Password based on 'SamAccountName' property. (MSA0013)"},
  {"time": "2019-09-24T16:25:17.824+00:00", "type": "verbose", "message": "[ADFS01-EUW1-SRV]:                            [[ADManagedServiceAccount]AdfsGmsa] AD Managed Service Account 'AdfsGmsa' was not found. (MSA0005)"},
  {"time": "2019-09-24T16:25:17.918+00:00", "type": "verbose", "message": "[ADFS01-EUW1-SRV]:                            [[ADManagedServiceAccount]AdfsGmsa] Adding AD Managed Service Account 'AdfsGmsa'. (MSA0001)"},
  {"time": "2019-09-24T16:25:18.528+00:00", "type": "verbose", "message": "[ADFS01-EUW1-SRV]: LCM:  [ End    Set      ]  [[ADManagedServiceAccount]AdfsGmsa]  in 0.8980 seconds."},
  {"time": "2019-09-24T16:25:18.528+00:00", "type": "error", "message": "PowerShell DSC resource MSFT_ADManagedServiceAccount  failed to execute Set-TargetResource functionality with error message: System.InvalidOperationException: Error adding AD Managed Service Account 'AdfsGmsa'. (MSA0012) ---> Microsoft.ActiveDirectory.Management.ADIdentityAlreadyExistsException: The specified account already exists ---> System.ServiceModel.FaultException: The supplied entry already exists.\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.ActiveDirectory.Management.AdwsConnection.ThrowExceptionForExtendedError(String extendedErrorMessage, Exception innerException)\r\n   at Microsoft.ActiveDirectory.Management.AdwsConnection.ThrowExceptionForErrorCode(String message, String errorCode, String extendedErrorMessage, Exception innerException)\r\n   at Microsoft.ActiveDirectory.Management.AdwsConnection.ThrowExceptionForFaultDetail(FaultDetail faultDetail, FaultException faultException)\r\n   at Microsoft.ActiveDirectory.Management.AdwsConnection.ThrowException(AdwsFault adwsFault, FaultException faultException)\r\n   at Microsoft.ActiveDirectory.Management.AdwsConnection.Create(ADAddRequest request)\r\n   at Microsoft.ActiveDirectory.Management.ADWebServiceStoreAccess.Microsoft.ActiveDirectory.Management.IADSyncOperations.Add(ADSessionHandle handle, ADAddRequest request)\r\n   at Microsoft.ActiveDirectory.Management.ADActiveObject.Create()\r\n   at Microsoft.ActiveDirectory.Management.Commands.ADNewCmdletBase`3.ADNewCmdletBaseProcessCSRoutine()\r\n   at Microsoft.ActiveDirectory.Management.CmdletSubroutinePipeline.Invoke()\r\n   at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.ProcessRecord()\r\n   --- End of inner exception stack trace --- "},

```

#### Suggested solution to the issue

There is currently a single try/catch block around all the code in the `Get-TargetResource` function, which is catching errors from both `Get-ADObjectParentDN` as well as `Get-ADObject`. There should be separate try/catch blocks around each of these functions, with appropriate error handling for each one.
 
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
ADManagedServiceAccount AdfsGmsa {
    ServiceAccountName = $ServiceAccountName
    AccountType        = 'Group'
    Credential         = $Credential
    Description        = 'ADFS Server Farm Group Managed Service Account'
}
```

#### The operating system the target node is running

```
OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

#### Version and build of PowerShell the target node is running

```
PSVersion                      5.1.17763.592
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.592
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

#### Version of the DSC module that was used ('dev' if using current dev branch)

4.0.0.0

### LINKED ISSUE #515: ADManagedServiceAccount: Proposed Breaking Change
I am currently working on the `ADManagedServiceAccount` resource to fix issues #511 and #512. Going through the code, there are other issues with it which I am taking the opportuntity to fix, including the following breaking changes:

Breaking:

- `AccountType` parameter ValidateSet changed from `('Group', 'Single')` to `('Group', 'Standalone')` - `Standalone` is the correct terminology. ref: https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/service-accounts.
- `AccountType` parameter default of `Single` removed. - Enforce positive choice of account type.
- `MembershipAttribute` parameter ValidateSet member `SID` changed to `ObjectSid` to match result property of Get-AdObject. Current code does not work if `SID` is specified.
- `AccountTypeForce` parameter removed - unnecessary complication. With the current code for this in place, if the `AccountType` is changed without specifying this parameter, the change will not apply, but the DSC will still complete successfully. A warning is written to the log, but unless you are looking for it you won't see it. I don't think this is a good model, and none of the other resources use it.
- Renamed `Members` parameter to `ManagedPasswordPrincipals` - to closer match `Get-AdServiceAccount` result property `PrincipalsAllowedToRetrieveManagedPassword`. This is so that a `DelegateToAccountPrincipals` parameter can be added later.

I also intend to subsequently add the following missing parameters to the resource that are directly supported by the `ADServiceAaccount` PowerShell cmdlets:

- AccountExpirationDate
- AccountNotDelegated
- CompoundIdentitySupported
- DelegateToAccountPrincipals (PrincipalsAllowedToDelegateToAccount)
- HomePage
- ServicePrincipalNames
- TrustedForDelegation
- Enabled

Any comments?

### PR DESCRIPTION
**Pull request by X-Guardian**
#### Pull Request (PR) description

This PR makes multiple changes to the `ADManagedServiceAccount` resource:

- `KerberosEncryptionType` property added.
- `AccountType` parameter ValidateSet changed from `('Group', 'Single')` to `('Group', 'Standalone')` - `Standalone` is the correct terminology. ref: https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/service-accounts.
- `AccountType` parameter default of `Single` removed. - Enforce positive choice of account type.
- `MembershipAttribute` parameter ValidateSet member `SID` changed to `ObjectSid` to match result property of Get-AdObject. Current code does not work if `SID` is specified.
- `AccountTypeForce` parameter removed - unnecessary complication.
- `Members` parameter renamed to `ManagedPasswordPrincipals` - to closer match `Get-AdServiceAccount` result property `PrincipalsAllowedToRetrieveManagedPassword`. This is so that a `DelegateToAccountPrincipals` parameter can be added later.
- Common `Compare-ResourcePropertyState` function used to replace function specific `Compare-TargetResourceState` and code refactored.
- Code refactored to remove requirement for separate `New-ADServiceAccountHelper` function.
- Individual try/catch blocks added around each cmdlet call.
- Property/parameter lists sorted into alphabetical order.
- Resource unit tests refactored to use nested contexts and follow the logic of the module.
- Resource Integration tests added.

Note: the change to using `Compare-ResourcePropertyState` is dependent on PR #514 being merged for all the tests to pass.

#### This Pull Request (PR) fixes the following issues

- Fixes #511 
- Fixes #512
- Fixes #515

#### Task list

- [x] Added an entry under the Unreleased section in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in resource directory README.md.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Conceptual help topic added/updated (cultureFolder\about_ResourceName.help.txt).
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/activedirectorydsc/517)

### CODE REVIEW

**Comment by X-Guardian** [comment]
Sorry this PR ended up being a major change, but the more I looked at the resource, the more I felt needed changing. It might be worth just reviewing this as a new resource.

**Comment by johlju** [comment]
I will get to this soon! 😄

**Comment by X-Guardian** [comment]
Hi @johlju, I was hoping that we could get this PR into the next release. Are you able to review yet?

**Comment by johlju** [comment]
I will review it on Friday. Sorry it taken so long, it has been a long days at work and had to spend time with family the last weekends. :)

**Comment by X-Guardian** [comment]
Cheers @johlju, sorry to hassle.

No rush now, as I doubt we will get it done before the next release, and with the coming change to more ad-hoc releases after this one, we won't have to wait another 6 weeks after that.

**Comment by kilasuit** [comment]
> My opinion is that you only need to see log messages for properties which are not in the desired state, which is what I am doing here.

What you really want is to query which Resources are not in the Desired State not all the logs themselves

This can be done with the following line of code

`Get-DscConfigurationStatus | Select-Object ResourcesNotInDesiredState`

**Comment by johlju** [comment]
@kilasuit we are talking about when this resource (the Test function for example) is comparing the desired state properties against the current state properties. Not getting all the resources currently not in desired state. :)

**Comment by johlju** [comment]
In SqlServerDsc the integration tests are built to run in order so one integration tests is dependent on another, mostly to speed up testing. Maybe we can have an integration test for the ADKDSKey that can be run prior to this integration tests (manually to start)?

**Comment by X-Guardian** [comment]
I've raised PR #526 to add `ADKDSKey` integration tests. If you run this before the `ADManagedServiceAccount` integration tests, they will run without error.

**Comment by johlju** [comment]
@X-Guardian Nah, sorry. The SqlServerDsc tests are run in AppVeyor CI only. I haven't tried running them locally, I usually kick them off in my own AppVeyor account before sending in a PR.

For now it works running them manually here. 🙂

**Comment by johlju** [comment]
@X-Guardian Awesoem work on this! And thank you for becoming a maintainer for this module!

**Comment by X-Guardian** [comment]
@johlju, any chance we can publish a release with this update?

**Comment by johlju** [comment]
@X-Guardian it is only possible if @mgreenegit have time to do an out-of-band release. When this is repo is moved to DSC Community by @gaelcolas the we can change the pipeline to release it automatically.

**Pull request merged**
