### PR TITLE
xADGroup: Fix Issue #166

### LINKED ISSUE #166: ADGroup: Throws incorrect error message when MembersToInclude syntax is wrong
When adding a member to a group using the SamAccountName.

```powershell
xADGroup 'AddClusterNetworkObjectToActiveDirectoryCreateClusterVirtualComputerObjects'
{
    GroupName        = 'Active Directory Create Cluster Virtual Computer Objects'
    Path             = 'OU=Groups,OU=Europe,OU=Regions,DC=companylab,DC=se'
    MembersToInclude = 'TESTCLU01'

    Credential       = $DomainAdministratorCredential

    DependsOn        = '[xADComputer]TESTCLU01'
}
```

It throws an error indicating it tried to create the group again.

```
VERBOSE: [sql01]: LCM:  [ Start  Test     ]  [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-]
VERBOSE: [sql01]:                            [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-] Retrieving group membership based on 'SamAccountName' property.
VERBOSE: [sql01]:                            [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-] Checking for 'Included' members.
VERBOSE: [sql01]:                            [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-] Member 'testclu01' is not in the desired state.
VERBOSE: [sql01]:                            [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-] Group membership is NOT in the desired state.
VERBOSE: [sql01]: LCM:  [ End    Test     ]  [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-]  in 0.1400 seconds.
VERBOSE: [sql01]: LCM:  [ Start  Set      ]  [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-]
VERBOSE: [sql01]:                            [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-] Updating AD Group 'Active Directory Create Cluster Virtual Computer Objects'
VERBOSE: [sql01]:                            [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-] Retrieving group membership based on 'SamAccountName' property.
VERBOSE: [sql01]:                            [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-] Checking for 'Explicit' members.
VERBOSE: [sql01]:                            [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-] Checking for 'Included' members.
VERBOSE: [sql01]:                            [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-] Member 'testclu01' is not in the desired state.
VERBOSE: [sql01]:                            [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-] Adding '1' member(s) to AD group 'Active Directory Create Cluster Virtual Computer Objects'.
VERBOSE: [sql01]:                            [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-] AD Group 'Active Directory Create Cluster Virtual Computer Objects' was not found
VERBOSE: [sql01]:                            [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-] Adding AD Group 'Active Directory Create Cluster Virtual Computer Objects'
The specified group already exists
    + CategoryInfo          : NotSpecified: (CN=Active Direc...ompanylab,DC=se:) [], CimException
    + FullyQualifiedErrorId : ActiveDirectoryServer:1318,Microsoft.ActiveDirectory.Management.Commands.NewADGroup
    + PSComputerName        : sql01
```

If changing the configuration to use the distinguished name for the member to add, it correctly adds the member and does not try to create the group.

```powershell
xADGroup 'AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects'
{
    GroupName        = 'Active Directory Create Cluster Virtual Computer Objects'
    Path             = 'OU=Groups,OU=Europe,OU=Regions,DC=companylab,DC=se'
    MembersToInclude = 'CN=TESTCLU01,OU=Cluster Computer Objects,OU=Europe,OU=Regions,DC=companylab,DC=se'

    Credential       = $DomainAdministratorCredential

    DependsOn        = '[xADComputer]TESTCLU01'
}
```

``` 
VERBOSE: [sql01]: LCM:  [ Start  Test     ]  [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-]
VERBOSE: [sql01]:                            [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-] Retrieving group membership based on 'SamAccountName' property.
VERBOSE: [sql01]:                            [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-] Checking for 'Included' members.
VERBOSE: [sql01]:                            [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-] Member 'cn=testclu01,ou=cluster computer objects,ou=europe,ou=regions,dc=companylab,dc=se' is not in the desired state.
VERBOSE: [sql01]:                            [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-] Group membership is NOT in the desired state.
VERBOSE: [sql01]: LCM:  [ End    Test     ]  [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-]  in 0.2190 seconds.
VERBOSE: [sql01]: LCM:  [ Start  Set      ]  [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-]
VERBOSE: [sql01]:                            [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-] Updating AD Group 'Active Directory Create Cluster Virtual Computer Objects'
VERBOSE: [sql01]:                            [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-] Retrieving group membership based on 'SamAccountName' property.
VERBOSE: [sql01]:                            [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-] Checking for 'Explicit' members.
VERBOSE: [sql01]:                            [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-] Checking for 'Included' members.
VERBOSE: [sql01]:                            [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-] Member 'cn=testclu01,ou=cluster computer objects,ou=europe,ou=regions,dc=companylab,dc=se' is not in the desired state.
VERBOSE: [sql01]:                            [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-] Adding '1' member(s) to AD group 'Active Directory Create Cluster Virtual Computer Objects'.
VERBOSE: [sql01]: LCM:  [ End    Set      ]  [[xADGroup]AddClusterNetowrkObjectToActiveDirectoryCreateClusterVirtualComputerObjects::[SqlAlwaysOnCluster]-::[SqlAlwaysOnCluster]-]  in 0.2030 seconds.
```

1. I would expect the resource to not try to create the group again if it encounters an error. If possible.
1. The documentation should be updated to reflect that the distinguished name should be used.

### PR DESCRIPTION
**Pull request by devopsjesus**
#### Pull Request (PR) description
This PR fixes issue #166 to have the resource throw the correct error when adding a member object that does not exist in the domain to a group that does exist.

#### This Pull Request (PR) fixes the following issues
- Fixes #166 

#### Task list
- [X] Added an entry under the Unreleased section in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in resource directory README.md.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [X] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [X] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/429)

### CODE REVIEW

**Comment by johlju** [comment]
The repo has been renamed to ActiveDirectoryDsc and all resource names have been renamed removing the 'x'. Please make sure this PR is updated accordingly when you rebase. 🙂 Let me know if you need any help with this.

**Comment by johlju** [comment]
@devopsjesus Do you have time to work on this? Love to get this in before next release in a week. If you don't have time, I can look at getting this over the finish line if you like. 🙂

**Comment by devopsjesus** [comment]
hey! sorry for the extended absence, I've been on leave and otherwise pre-occupied 😨 I plan on getting to this within the next couple days

**Comment by johlju** [comment]
@devopsjesus welcome back! 🙂 Awesome, that would be great!

**Comment by johlju** [comment]
@devopsjesus do you think you have time to work on this? 🙂

**Comment by johlju** [comment]
No worries. Thanks for looking at this. 🙂

**Comment by johlju** [comment]
@devopsjesus I think this change is covered in PR #497. 🤔

**Pull request closed without merging**
