### PR TITLE
ADDomainController: Added InstallDns to promote without installing DNS

### LINKED ISSUE #87: ADDomainController: Add the ability to create forest using existing Microsoft and/or BIND DNS server

### PR DESCRIPTION
**Pull request by rcarboneras**
#### Pull Request (PR) description
My customer is using a third party DNS. This resource by default install DNS service and add the loopback ip as the default address

Scenario: You need to promote a server to an existing domain working with an external DNS (Bluecat)

Install-ADDSDomainController -InstallDNS:$false would be used in this scenario.

#### This Pull Request (PR) fixes the following issues
- Fixes  #87

#### Task list

- [x] Added an entry under the Unreleased section in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in resource directory README.md.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/439)

### CODE REVIEW

**Comment by johlju** [comment]
@rcarboneras The repo has been renamed to ActiveDirectoryDsc and all resource names have been renamed removing the 'x'. Please make sure this PR is updated accordingly when you rebase. 🙂 Let me know if you need any help with this.

**Comment by johlju** [comment]
@rcarboneras Let me knosw if you need any help with this change. Happy to help.

**Comment by johlju** [comment]
There are still merge conflicts. Could you please rebase against branch dev using `git rebase` (not by using `git pull` or `git merge`, to keep the commit history). If you don't know how to rebase your local dev and working branch, please look at how to [Resolve merge conflicts](https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts).
Let me know if you need any assistance. 🙂

**Comment by johlju** [comment]
You might need to undo the last commit before rebasing. 🤔 It added the files in the entire repo.

**Comment by johlju** [comment]
@rcarboneras The renaming of this repo and all the resources made a rebase more difficult, so instead of rebasing, if you wish you can just add your changes to a new branch and send in a new PR based on that branch. 🙂

**Comment by johlju** [comment]
Out of curiosity I tried to rebase you branch, and it went better than I expected. 😄 The only problem was I had to look at the change log in the upstream dev branch (here in this repo) to validate what entries should go where and which already existed (but had been renamed/updated) so I didn't leave duplicates. 

I have a branch here now you can look at if it looks okay to you, then I can push it to the PR (to your working branch) if you like.
https://github.com/PowerShell/ActiveDirectoryDsc/compare/dev...johlju:debubg-InstallDns-after-rebase?expand=1

Let me know what you want to do Really want this PR to get over the finish line, since it is a great addition! 😃

**Comment by johlju** [comment]
@rcarboneras what are your thoughts of my comments above to resolve the merge conflicts? 🙂

**Comment by rcarboneras** [comment]
> @rcarboneras what are your thoughts of my comments above to resolve the merge conflicts? 🙂

Hello Johan, sorry for the delay to respond. Yes, it looked good for me, thanks :). I tried to merge your branch with my dev one but I'm not sure now if that was well done. There seems to have conflits yet, i'm trying to see why

**Comment by johlju** [comment]
@rcarboneras no worries. Best is to rebase (`git rebase`) against upstream dev. Using pull and merging will just make it worse I'm afraid. 🤔 

If you like I can help you, I can force push the branch I rebased over your branch, which will automatically update this PR as well. Then you just need to fetch your branch again.

**Comment by rcarboneras** [comment]
> @rcarboneras no worries. Best is to rebase (`git rebase`) against upstream dev. Using pull and merging will just make it worse I'm afraid. 🤔
> 
> If you like I can help you, I can force push the branch I rebased over your branch, which will automatically update this PR as well. Then you just need to fetch your branch again.

Yes please, do it, and lest see the results :)

**Comment by johlju** [comment]
There you go. Normally this is much simpler, we messed up a lot for you by renaming everything. 😄 

Now if you do this
```
# replace 'my' with the remote of your fork (git remote -v)
git fetch my dev
git rebase my/dev
```

Then
```
git log
```

It should look like this (remote names might be different)

```
commit 5bdaf8655a1c2dac91dd678d89474fb5d5870044 (HEAD -> dev, origin/dev, origin/HEAD, my/dev)                                                                                                          Author: Raul Microsoft <racarb@microsoft.com>
Date:   Tue Jul 23 22:42:45 2019 +0200

    InstallDns Example Changed
```

If it doesn't, then just clone your fork again and checkout dev and you should be back in a good state.

**Comment by johlju** [comment]
There are a few more review comments to resolve I think form the previous reviews.

Let me know if you need any more assistance, happy to help.

**Comment by johlju** [comment]
I took liberty to rebased the branch after the latest release so the merge conflicts was resolved again. Hope you didn't mind. 🙂 

Let me know if you don't have time to work on this PR.

**Comment by rcarboneras** [comment]
> I took liberty to rebased the branch after the latest release so the merge conflicts was resolved again. Hope you didn't mind. 🙂
> 
> Let me know if you don't have time to work on this PR.

Hi Johan, thank you, I don't mind at all. I'm on vacation and unfortunately I don't have much time at the moment to work on this, at least until the 15th :(

**Comment by johlju** [comment]
That explains it 😃 Continue enjoy your vacation and you can pick this up when you are back. If you feel you can't work on this sometime after the 15:th. Please let me know. 🙂

**Comment by johlju** [comment]
@rcarboneras I helped getting this over the finish line. Wanted to have this added before next release. Thank you for you contribution! Much appreciated! 😃

**Pull request merged**
