### PR TITLE
BREAKING CHANGE: xADRecycleBin refactor into xADOptionalFeature

### LINKED ISSUE #162: ADOptionalFeature: New Resource (to replace ADRecycleBin)
I'm about to create a pull request for a new resource to support any ADOptionalFeature.

I needed to be able to activate the "Privileged Access Management Feature" on a domain controller and realised this feature didn't already exist.

The question is should this resource supersede xADRecycleBin?

Perhaps its easier for people not in the know to simply turn on the recycle bin this way, but is it not better to have a generic resource and pass "Recycle Bin Feature" as the key parameter?

Discuss :)

### PR DESCRIPTION
**Pull request by rdbartram**
#### Pull Request (PR) description
Modifies the existing xADRecycleBin feature to support all known and future AD Optional Feature inc PIM. For backwards compatibility, a composite resource has been added. This avoids creating a breaking change.

#### This Pull Request (PR) fixes the following issues
- Fixes #162 

#### Task list
- [x] Added an entry under the Unreleased section in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in resource directory README.md.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/activedirectorydsc/462)

### CODE REVIEW

**Comment by johlju** [comment]
@rdbartram awesome job on this one! 😃

**Comment by johlju** [comment]
My last comment we could add to an issue to fix later if you like. 🙂

**Comment by rdbartram** [comment]
To be honest, thats a carry over from the older resource. The only two optional features today are ad recycle bin and pim which are both at the forest level. But if there were features at the domain level then that would break it. For consistency i'll make sure its call the domainnamingmaster everywhere and accept your integration tests

**Comment by johlju** [comment]
Cool, sounds good! The problem with a new feature at the domain level we put to the future. 😃

**Comment by rdbartram** [comment]
Ok, i'm pretty sure thats everything now. all tests pass. 100% coverage. hopefully we are a go!

**Comment by johlju** [comment]
Thanks again for helping to get the issue resolved, and getting new functionality into the module!

**Pull request merged**
