### PR TITLE
AdReplicationSite: Adding description attribute, will create integration tests

### LINKED ISSUE #355: ADReplicationSite: Integration tests is missing for this resource
We should add integration tests for this resource.

### LINKED ISSUE #500: ADSiteResource: Add description attribute
#### Details of the scenario you tried and the problem that is occurring
Would like to be able to set the site description via DSC

#### Verbose logs showing the problem
N/A - new attribute

#### Suggested solution to the issue
Add ability to set the description on an AD Site resource

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
NA
```

#### The operating system the target node is running
N/A

#### Version and build of PowerShell the target node is running
N/A

#### Version of the DSC module that was used ('dev' if using current dev branch)
Dev

### LINKED ISSUE #502: ADReplicationSite: The value returned for RenameDefaultFirstSiteName is wrong
Current the value for `RenameDefaultFirstSiteName` is always returned as an empty string. That does not match the type in the schema.mof. This should return the value of the parameter `RenameDefaultFirstSiteName` (which defaults to `$false`).

https://github.com/PowerShell/ActiveDirectoryDsc/blob/ae42a2cb0eecb4b5f4f2abcb74edd5de58bb20a6/DSCResources/MSFT_ADReplicationSite/MSFT_ADReplicationSite.psm1#L38

### PR DESCRIPTION
**Pull request by 1800Zeta**
#### Pull Request (PR) description
This PR will add the ability to configure a Replication Site Description. Will also add integration testing

#### This Pull Request (PR) fixes the following issues
Fixes #500 
Fixes #355 
Fixes #502 

#### Task list
- [x] Added an entry under the Unreleased section in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in resource directory README.md.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Conceptual help topic added/updated (cultureFolder\about_ResourceName.help.txt).
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/activedirectorydsc/501)

### CODE REVIEW

**Comment by 1800Zeta** [comment]
The CodeCov is yellow on a couple of lines where I set a variable value which is why it's 90%. Not sure exactly how to nail those so they are green.

**Comment by 1800Zeta** [comment]
Thanks @johlju will work on those changes for you.

**Comment by johlju** [comment]
I will continue the review as soon as I can, hopefully tomorrow. 🙂

**Comment by johlju** [comment]
Just small things left! Awesome work! 😃

**Pull request merged**
