### PR TITLE
BREAKING CHANGE: Rename module to ActiveDirectoryDsc

### LINKED ISSUE #312: ActiveDirectoryDsc: Rename module from xActiveDirectory
Once community feels comfortable that this module follows the style guideline and test guidelines (minus the integration tests we can't enforce yet), then let's rename this module.

See issue https://github.com/PowerShell/xActiveDirectory/issues/172 that should be closed first before this one.

### PR DESCRIPTION
**Pull request by ChrisLGardner**
#### Pull Request (PR) description
Renames all resources and files to remove the x notation. 

#### This Pull Request (PR) fixes the following issues
Fixes #312 

#### Task list
- [x] Added an entry under the Unreleased section in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in resource directory README.md.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xactivedirectory/447)

### CODE REVIEW

**Comment by ChrisLGardner** [comment]
I need to update the changelog but want to kick off a build to see if I've missed anything or broken anything. I'll have a look at it a bit later today once the build finishes to see if anything is wrong.

**Comment by johlju** [comment]
It's gonna fail here in AppVeyor until this repo is renamed. But you can rename your fork and connect it to you own AppVeyor free account and run the tests. 🤔

**Comment by johlju** [comment]
Let me know if I can be of any help. Thank you for sending this in!

**Comment by johlju** [comment]
This seems to pass all the tests when I ran in in my fork https://ci.appveyor.com/project/johlju/activedirectorydsc/builds/26206472.

@ChrisLGardner Awesome work! I will review as soon as I can. It will probably take several days to review.

**Comment by johlju** [comment]
I think I will have more time to review this one tomorrow.

**Comment by johlju** [comment]
Closing and reopening to kick off the tests again.

**Comment by johlju** [comment]
Reopening again to kick off tests after repo rename.

**Comment by johlju** [comment]
Closing and reopening after AppVeyor has been updated.

**Pull request merged**
