### PR TITLE
ADUser: Remove unused non-mandatory parameters from the Get-TargetResource

### LINKED ISSUE #293: ADUser: Remove unused non-mandatory parameters from the Get-TargetResource function
According to DSC Resource Style Guidelines & Best Practices there should be [only mandatory parameters](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#get-targetresource-should-not-contain-unused-non-mandatory-parameters) in the Get-TargetResource function.
The unused non-mandatory parameters should be removed.

### PR DESCRIPTION
**Pull request by SSvilen**
#### Pull Request (PR) description
According to DSC Resource Style Guidelines & Best Practices there should be only mandatory parameters in the Get-TargetResource function.
The unused non-mandatory parameters are removed.

#### This Pull Request (PR) fixes the following issues
- Fixes #293 

#### Task list
- [x] Added an entry under the Unreleased section in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in resource directory README.md.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Conceptual help topic added/updated (cultureFolder\about_ResourceName.help.txt).
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/activedirectorydsc/487)

### CODE REVIEW

**Comment by johlju** [comment]
Thank you for this @SSvilen! Just some minor comments, 😃

**Comment by X-Guardian** [comment]
Are you sure this change can work guys? Both `Test-TargetResource` and `Set-TargetResource` call `Get-TargetResource` with their full list of specified parameters. `Get-AdUser` only returns values for properties you have explicitly asked for.
Check the AppVeyor build as for some reason none of the unit tests are running. Example:

```
Executing script C:\projects\activedirectorydsc\Tests\Unit\MSFT_ADUser.Tests.ps1
VERBOSE: Tests in category 'Tests' will be skipped unless $env:CONFIGURATION is set to 'Tests'.
```

**Comment by johlju** [comment]
I think it works. Get-TargetResource should always return all the properties regardless of the passed parameters. This could builds the properties that should be returned.

https://github.com/PowerShell/ActiveDirectoryDsc/blob/9a190e2c8c74ff7942409d3081144a6c2b182bf5/DSCResources/MSFT_ADUser/MSFT_ADUser.psm1#L494-L508

Not sure if the unit test actually test all the properties. That could be another PR which could be covered by the issue https://github.com/PowerShell/ActiveDirectoryDsc/issues/488.

**Comment by X-Guardian** [comment]
Ok, yes you are right. ignore me.

**Comment by johlju** [comment]
@SSvilen my example above had an error, the third command should be `git rebase origin/dev`, I updated it. Run it again and see if it works. Sorry about that.

**Comment by johlju** [comment]
A rebase basically takes the commits in the dev branch and then replays your commits on top of it one by one. 

Strange that you see 15 commits. There are only 8 commits in this PR, but it should only be 7, so I think if you try the rebase one more time I hope it will be correct. If it is not correct I will look at it. You should not need to make another branch or PR. Let’s try to avoid that. So try to do the rebase again, and we will see the outcome :)

**Comment by johlju** [comment]
Let me know if another rebase did not help and I will help you look at it.

**Comment by johlju** [comment]
Ah, then I understand that you got more commits, I did the same mistake when I did the rebase first time too. 😊 No worries, it looks fine now, it’s no problem with the extra commits. I squash all the commits when I merge so they will not be a problem. 

Awesome work! We learn by mistakes too 😊

I continue the review tomorrow.

**Comment by johlju** [comment]
@SSvilen awesome work on this! Thank you! 😃

**Pull request merged**
